# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "less-form"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["easonhan"]
  s.date = "2013-04-20"
  s.description = "form element wrapper for selenium-webdriver, make your test code more readable and make your form element handing easy"
  s.email = "nbkhic@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "chromedriver.log",
    "lib/less-form.rb",
    "lib/less-form/button.rb",
    "lib/less-form/checkbox.rb",
    "lib/less-form/element.rb",
    "lib/less-form/errors.rb",
    "lib/less-form/form.rb",
    "lib/less-form/options.rb",
    "lib/less-form/radio.rb",
    "lib/less-form/select.rb",
    "lib/less-form/table.rb",
    "lib/less-form/text_field.rb",
    "lib/webdriver-ext/element.rb",
    "spec/html/form.html",
    "spec/less-form_spec.rb",
    "spec/spec_helper.rb",
    "usage.rb"
  ]
  s.homepage = "https://github.com/easonhan007/less-form"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.16"
  s.summary = "form element wrapper for selenium-webdriver"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<selenium-webdriver>, ["~> 2.31.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_development_dependency(%q<selenium-webdriver>, ["~> 2.31.0"])
    else
      s.add_dependency(%q<selenium-webdriver>, ["~> 2.31.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, ["~> 2.13.0"])
      s.add_dependency(%q<selenium-webdriver>, ["~> 2.31.0"])
    end
  else
    s.add_dependency(%q<selenium-webdriver>, ["~> 2.31.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, ["~> 2.13.0"])
    s.add_dependency(%q<selenium-webdriver>, ["~> 2.31.0"])
  end
end

